### ISSUE TITLE
Bomb Grid misaligned in oTree 2.0.18

### ISSUE THREAD

**Issue by clintmckenna** [felixholzmeister/bret#2]
Hi, the grid seems to be split up in a weird way after updating oTree. Any thoughts? Thanks!

![bret](https://user-images.githubusercontent.com/10391468/35694903-cea16e6c-0750-11e8-909a-18a64e938b33.PNG)

**Comment by felixholzmeister** [comment]
Hi,

Sorry for these inconveniences.
I’m working on it and will send you an updated version later today or tomorrow.
Some of the styles need to be updated due to the update to Bootstrap v4.

Best,
Felix

Von: clintmckenna [mailto:notifications@github.com]
Gesendet: Donnerstag, 1. Februar 2018 19:08
An: felixholzmeister/bret <bret@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [felixholzmeister/bret] Bomb Grid misaligned in oTree 2.0.18 (#2)


Hi, the grid seems to be split up in a weird way after updating oTree. Any thoughts? Thanks!

[bret]<https://user-images.githubusercontent.com/10391468/35694903-cea16e6c-0750-11e8-909a-18a64e938b33.PNG>

**Comment by felixholzmeister** [comment]
updates styles to be compatible with oTree v2
